# Wittgenstein Markup Language (`.wit`)
The markup language dedicated to writing complicated, nested lists. You could use it to write the next _Tractatus Logico-Philosophicus_ and not have to worry about the numberings (they're all done automatically). 🙂

## What Wittgenstein Does
Aren't truth tables a great way of organizing the values of logical expressions?
Don't forget that Wittgenstein _invented_ truth tables as (basically) an aside in his _Tractatus Logico-Philosophicus_. The organizational structure of that work itself is also a great organizational system — it provides a powerful way of organizing related comments/statements/propositions/sections. Whoever wants to make notes quickly in that style can now rejoice, because the Wittgenstein Markup Language takes care of all the hard numbering/sub-sectioning work!

Why not just use Markdown? Markdown doesn't support nested numbering like the following:

1* First item
    * First item's first sub-item
* Second Item

If you _tried_ to do it, you might _write_ something like this:

```markdown
1. First item
    1.1. First item's first sub-item
2. Second Item
```

But you would unfortunately get something that looks like this:
1. First item
    1.1. First item's first sub-item
2. Second Item

While you could manage the numbering by hand manually via [some hacky solutions](https://meta.stackexchange.com/questions/85474/how-to-write-nested-numbered-lists), if you later need to _insert_ an item, you have to do a lot of renumbering. It sucks and is not something you can do easily once you start having to manage larger nested lists.

Our renumbering concern applies to the normal ordered lists that Markdown supports. They might seem nice in principle:
```markdown
1. First Item
2. Second Item
3. Third Item
```

(Which produces the following:)
1. First Item
2. Second Item
3. Third Item

But, again, there's something really annoying about having to renumber extensive lists.

So, as an alternate syntax, how about this instead?:
```wittgenstein
1* First Item
* Second Item
* Third Item
```
It should be enough to show that the intent was an ordered list using numbers with the _first_ list element by simply doing `1*` and using only `*` for the subsequent list elements. (In the future, we ought to be able to support `a*`, too.)

And, it works:

1* First Item
* Second Item
* Third Item

Now, taking the previous innovation in mind, we added support for our numbered nesting simply by indicating each level clearly.

So, here is the original markup for the first example we gave:
```wittgenstein
1* First item
    * First item's first sub-item
* Second Item
```

And it works, too, because this very README used this Wittgenstein-influenced markup language to produce its examples. (The very first example of a list we gave in this README was originally written in this style.)

So, basically, when nesting, indent (with 4 spaces) and use `*`s as you would normally, and Wittgenstein does the rest! Just remember to preface your first star with a `1`. 


## How Wittgenstein Works
Keep in mind this is a proof-of-concept written on a Saturday night. Currently, it's a simply Python3 script that does a relatively light transformation on the lines of an inputted text file that start with `*` or `1*` (excluding whitespace to also handle lines that correspond to sub-items).

It was first a simple generator of indentions for plaintext files and then I decided I wanted to be able to generate Markdown files. Since Markdown supports HTML, the way Wittgenstein works _for Markdown_ is to simply generate HTML tags and let CSS handle the numbering. (Since I added support for Markdown _after_ I had figured out the more-straightforward indention logic for plaintext (which didn't actually require me to do any lookaheads or lookbacks), the logic I added for handling nested HTML tags is confusing as heck — but it works.)

Apparently, GitHub doesn't support `<styles>` in Markdown, so the numbering appears slightly incorrect there — instead of `1.1.1.`, we get `1.i.a`. 😭 

There's still support for the plain, indention-based numbering. I'm leaving the HTML mode as the default because it is more impressive.


## Complicated Examples
The following is a complicated nesting example (I'm actually using this README to hold the test cases since this README is written in the `.wit` markup language and is simple being exported to Markdown.).

1* The world is all that is the case.
    * The world is the totality of facts, not of things.
        * The world is determined by the facts, and by their being all the facts.
        * For the totality of facts determines what is the case, and also whatever is not the case.
        * The facts in logical space are the world.
    * The world divides into facts.
        * Each item can be the case or not the case while everything else remains the same.

And because I don't wish to include the full _Tractatus Logico-Philosophicus_ in this README, we'll provide an nesting edge-case:

1* This is a simple item
            * This is a complicated item with some empty parent nodes
        * This is actually a more complicated item
            * An earlier version had bugs and gave the wrong numbers in these situations
* This is another simple item
    * We want to make sure that this item (and its successors) is numbered properly
        * Is this one numbered correctly?
            * What about this one?
            * Don't forget this one!
* _What about support for Markdown syntax in the items themselves?_
*{id} If I want to be _able_ to link, I have to give the line an ID
    *{nested_id} Don't forget nested ones!
* Then, if I want to make a link, I can simply refer to @{id}.
    * I can also refer to @{nested_id} (as well as @{id} in the same line)
        * And I can refer to @{forward_ref}

*{forward_ref} Despite the line break above, _we_ have decided we want to consider this part of the same list to allow for more formatting flexibility


* BUT, this line starts a new list (because there's two blank lines) (and isn't numbered because it doesn't start with `1*`)

## Dependencies
```
pip3 install markdown
```


## Future Changes
* Support LaTeX as an output.
* Support `a*` listing.
* Support `N*` listing, where `N` is any number (right now we can only start at `1`)
* Support `w*` listing (one that uses the exact style of numbering that the _Tractatus Logico-Philosophicus_ does — though I like the style of this version more, we handle empty nodes differently than the TLP and end up with different numbers.)
* There's some other stuff I'd like have a markup language support (such as simple diagrams), though I'm undecided on a syntax for the time being — this project may grow to support other newish markup features.
* Support numbering in `>`s
